name: kagome_dart
description: Simple dart bindings to kagome
version: 1.0.0
homepage: "https://github.com/CaptainDario/kagome_dart"

environment:
  sdk: ">=2.17.6"
  flutter: ">=1.17.0"

dependencies:
  ffi: ^2.0.1
  tuple: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:


