


///Contains
enum PosUnidic {
	Pron,
	Adv,
	Aux,
	P_bind,
	P_adv,
	P_conj,
	P_case,
	P_nom,
	P_fin,
	V_g,
	V_bnd,
	N_aux,
	N_prop_g,
	N_prop_n_g,
	N_prop_n_f,
	N_prop_n_s,
	N_prop_p_g,
	N_prop_p_c,
	N_num,
	N_c_vs,
	N_c_vs_ana,
	N_c_g,
	N_c_adv,
	N_c_count,
	N_c_ana,
	Ai_g,
	Ai_bnd,
	Ana_tari,
	Ana_g,
	Ana_aux,
	Interj_fill,
	Interj_g,
	Suff_v,
	Suff_n_vs,
	Suff_n_g,
	Suff_n_adv,
	Suff_n_count,
	Suff_ai,
	Suff_ana,
	Conj,
	Pref,
	Ws,
	Supsym_aa_g,
	Supsym_aa_e,
	Supsym_g,
	Supsym_p,
	Supsym_bo,
	Supsym_bc,
	Supsym_c,
	Sym_g,
	Sym_ch,
	Adn,
	Unknown,
	Katakana,
	Kanbun,
	Hesitation,
	ErrorOmit,
	Dialect,
	Lat,
	NewUnknown,
}

///Convert a kagome output string (japanese) to an pos enum instance

Map<String, PosUnidic> jpToPosUnidic = {
	'代名詞' : PosUnidic.Pron,
	'副詞' : PosUnidic.Adv,
	'助動詞' : PosUnidic.Aux,
	'助詞-係助詞' : PosUnidic.P_bind,
	'助詞-副助詞' : PosUnidic.P_adv,
	'助詞-接続助詞' : PosUnidic.P_conj,
	'助詞-格助詞' : PosUnidic.P_case,
	'助詞-準体助詞' : PosUnidic.P_nom,
	'助詞-終助詞' : PosUnidic.P_fin,
	'動詞-一般' : PosUnidic.V_g,
	'動詞-非自立可能' : PosUnidic.V_bnd,
	'名詞-助動詞語幹' : PosUnidic.N_aux,
	'名詞-固有名詞-一般' : PosUnidic.N_prop_g,
	'名詞-固有名詞-人名-一般' : PosUnidic.N_prop_n_g,
	'名詞-固有名詞-人名-名' : PosUnidic.N_prop_n_f,
	'名詞-固有名詞-人名-姓' : PosUnidic.N_prop_n_s,
	'名詞-固有名詞-地名-一般' : PosUnidic.N_prop_p_g,
	'名詞-固有名詞-地名-国' : PosUnidic.N_prop_p_c,
	'名詞-数詞' : PosUnidic.N_num,
	'名詞-普通名詞-サ変可能' : PosUnidic.N_c_vs,
	'名詞-普通名詞-サ変形状詞可能' : PosUnidic.N_c_vs_ana,
	'名詞-普通名詞-一般' : PosUnidic.N_c_g,
	'名詞-普通名詞-副詞可能' : PosUnidic.N_c_adv,
	'名詞-普通名詞-助数詞可能' : PosUnidic.N_c_count,
	'名詞-普通名詞-形状詞可能' : PosUnidic.N_c_ana,
	'形容詞-一般' : PosUnidic.Ai_g,
	'形容詞-非自立可能' : PosUnidic.Ai_bnd,
	'形状詞-タリ' : PosUnidic.Ana_tari,
	'形状詞-一般' : PosUnidic.Ana_g,
	'形状詞-助動詞語幹' : PosUnidic.Ana_aux,
	'感動詞-フィラー' : PosUnidic.Interj_fill,
	'感動詞-一般' : PosUnidic.Interj_g,
	'接尾辞-動詞的' : PosUnidic.Suff_v,
	'接尾辞-名詞的-サ変可能' : PosUnidic.Suff_n_vs,
	'接尾辞-名詞的-一般' : PosUnidic.Suff_n_g,
	'接尾辞-名詞的-副詞可能' : PosUnidic.Suff_n_adv,
	'接尾辞-名詞的-助数詞' : PosUnidic.Suff_n_count,
	'接尾辞-形容詞的' : PosUnidic.Suff_ai,
	'接尾辞-形状詞的' : PosUnidic.Suff_ana,
	'接続詞' : PosUnidic.Conj,
	'接頭辞' : PosUnidic.Pref,
	'空白' : PosUnidic.Ws,
	'補助記号-ＡＡ-一般' : PosUnidic.Supsym_aa_g,
	'補助記号-ＡＡ-顔文字' : PosUnidic.Supsym_aa_e,
	'補助記号-一般' : PosUnidic.Supsym_g,
	'補助記号-句点' : PosUnidic.Supsym_p,
	'補助記号-括弧閉' : PosUnidic.Supsym_bo,
	'補助記号-括弧開' : PosUnidic.Supsym_bc,
	'補助記号-読点' : PosUnidic.Supsym_c,
	'記号-一般' : PosUnidic.Sym_g,
	'記号-文字' : PosUnidic.Sym_ch,
	'連体詞' : PosUnidic.Adn,
	'未知語' : PosUnidic.Unknown,
	'カタカナ文' : PosUnidic.Katakana,
	'漢文' : PosUnidic.Kanbun,
	'言いよどみ' : PosUnidic.Hesitation,
	'web誤脱' : PosUnidic.ErrorOmit,
	'方言' : PosUnidic.Dialect,
	'ローマ字文' : PosUnidic.Lat,
	'新規未知語' : PosUnidic.NewUnknown,
};

///Convert a kagome output string (english) to an pos enum instance
Map<String, PosUnidic> enToPosUnidic = {
	'Pron' : PosUnidic.Pron,
	'Adv' : PosUnidic.Adv,
	'Aux' : PosUnidic.Aux,
	'P.bind' : PosUnidic.P_bind,
	'P.adv' : PosUnidic.P_adv,
	'P.conj' : PosUnidic.P_conj,
	'P.case' : PosUnidic.P_case,
	'P.nom' : PosUnidic.P_nom,
	'P.fin' : PosUnidic.P_fin,
	'V.g' : PosUnidic.V_g,
	'V.bnd' : PosUnidic.V_bnd,
	'N.aux' : PosUnidic.N_aux,
	'N.prop.g' : PosUnidic.N_prop_g,
	'N.prop.n.g' : PosUnidic.N_prop_n_g,
	'N.prop.n.f' : PosUnidic.N_prop_n_f,
	'N.prop.n.s' : PosUnidic.N_prop_n_s,
	'N.prop.p.g' : PosUnidic.N_prop_p_g,
	'N.prop.p.c' : PosUnidic.N_prop_p_c,
	'N.num' : PosUnidic.N_num,
	'N.c.vs' : PosUnidic.N_c_vs,
	'N.c.vs.ana' : PosUnidic.N_c_vs_ana,
	'N.c.g' : PosUnidic.N_c_g,
	'N.c.adv' : PosUnidic.N_c_adv,
	'N.c.count' : PosUnidic.N_c_count,
	'N.c.ana' : PosUnidic.N_c_ana,
	'Ai.g' : PosUnidic.Ai_g,
	'Ai.bnd' : PosUnidic.Ai_bnd,
	'Ana.tari' : PosUnidic.Ana_tari,
	'Ana.g' : PosUnidic.Ana_g,
	'Ana.aux' : PosUnidic.Ana_aux,
	'Interj.fill' : PosUnidic.Interj_fill,
	'Interj.g' : PosUnidic.Interj_g,
	'Suff.v' : PosUnidic.Suff_v,
	'Suff.n.vs' : PosUnidic.Suff_n_vs,
	'Suff.n.g' : PosUnidic.Suff_n_g,
	'Suff.n.adv' : PosUnidic.Suff_n_adv,
	'Suff.n.count' : PosUnidic.Suff_n_count,
	'Suff.ai' : PosUnidic.Suff_ai,
	'Suff.ana' : PosUnidic.Suff_ana,
	'Conj' : PosUnidic.Conj,
	'Pref' : PosUnidic.Pref,
	'Ws' : PosUnidic.Ws,
	'Supsym.aa.g' : PosUnidic.Supsym_aa_g,
	'Supsym.aa.e' : PosUnidic.Supsym_aa_e,
	'Supsym.g' : PosUnidic.Supsym_g,
	'Supsym.p' : PosUnidic.Supsym_p,
	'Supsym.bo' : PosUnidic.Supsym_bo,
	'Supsym.bc' : PosUnidic.Supsym_bc,
	'Supsym.c' : PosUnidic.Supsym_c,
	'Sym.g' : PosUnidic.Sym_g,
	'Sym.ch' : PosUnidic.Sym_ch,
	'Adn' : PosUnidic.Adn,
	'Unknown' : PosUnidic.Unknown,
	'Katakana' : PosUnidic.Katakana,
	'Kanbun' : PosUnidic.Kanbun,
	'Hesitation' : PosUnidic.Hesitation,
	'ErrorOmit' : PosUnidic.ErrorOmit,
	'Dialect' : PosUnidic.Dialect,
	'Lat' : PosUnidic.Lat,
	'NewUnknown' : PosUnidic.NewUnknown,
};

///Convert english to japanese pos and vice versa
Map<String, String> jpEnConverter = {
	'代名詞' : 'Pron', 'Pron' : '代名詞',
	'副詞' : 'Adv', 'Adv' : '副詞',
	'助動詞' : 'Aux', 'Aux' : '助動詞',
	'助詞-係助詞' : 'P.bind', 'P.bind' : '助詞-係助詞',
	'助詞-副助詞' : 'P.adv', 'P.adv' : '助詞-副助詞',
	'助詞-接続助詞' : 'P.conj', 'P.conj' : '助詞-接続助詞',
	'助詞-格助詞' : 'P.case', 'P.case' : '助詞-格助詞',
	'助詞-準体助詞' : 'P.nom', 'P.nom' : '助詞-準体助詞',
	'助詞-終助詞' : 'P.fin', 'P.fin' : '助詞-終助詞',
	'動詞-一般' : 'V.g', 'V.g' : '動詞-一般',
	'動詞-非自立可能' : 'V.bnd', 'V.bnd' : '動詞-非自立可能',
	'名詞-助動詞語幹' : 'N.aux', 'N.aux' : '名詞-助動詞語幹',
	'名詞-固有名詞-一般' : 'N.prop.g', 'N.prop.g' : '名詞-固有名詞-一般',
	'名詞-固有名詞-人名-一般' : 'N.prop.n.g', 'N.prop.n.g' : '名詞-固有名詞-人名-一般',
	'名詞-固有名詞-人名-名' : 'N.prop.n.f', 'N.prop.n.f' : '名詞-固有名詞-人名-名',
	'名詞-固有名詞-人名-姓' : 'N.prop.n.s', 'N.prop.n.s' : '名詞-固有名詞-人名-姓',
	'名詞-固有名詞-地名-一般' : 'N.prop.p.g', 'N.prop.p.g' : '名詞-固有名詞-地名-一般',
	'名詞-固有名詞-地名-国' : 'N.prop.p.c', 'N.prop.p.c' : '名詞-固有名詞-地名-国',
	'名詞-数詞' : 'N.num', 'N.num' : '名詞-数詞',
	'名詞-普通名詞-サ変可能' : 'N.c.vs', 'N.c.vs' : '名詞-普通名詞-サ変可能',
	'名詞-普通名詞-サ変形状詞可能' : 'N.c.vs.ana', 'N.c.vs.ana' : '名詞-普通名詞-サ変形状詞可能',
	'名詞-普通名詞-一般' : 'N.c.g', 'N.c.g' : '名詞-普通名詞-一般',
	'名詞-普通名詞-副詞可能' : 'N.c.adv', 'N.c.adv' : '名詞-普通名詞-副詞可能',
	'名詞-普通名詞-助数詞可能' : 'N.c.count', 'N.c.count' : '名詞-普通名詞-助数詞可能',
	'名詞-普通名詞-形状詞可能' : 'N.c.ana', 'N.c.ana' : '名詞-普通名詞-形状詞可能',
	'形容詞-一般' : 'Ai.g', 'Ai.g' : '形容詞-一般',
	'形容詞-非自立可能' : 'Ai.bnd', 'Ai.bnd' : '形容詞-非自立可能',
	'形状詞-タリ' : 'Ana.tari', 'Ana.tari' : '形状詞-タリ',
	'形状詞-一般' : 'Ana.g', 'Ana.g' : '形状詞-一般',
	'形状詞-助動詞語幹' : 'Ana.aux', 'Ana.aux' : '形状詞-助動詞語幹',
	'感動詞-フィラー' : 'Interj.fill', 'Interj.fill' : '感動詞-フィラー',
	'感動詞-一般' : 'Interj.g', 'Interj.g' : '感動詞-一般',
	'接尾辞-動詞的' : 'Suff.v', 'Suff.v' : '接尾辞-動詞的',
	'接尾辞-名詞的-サ変可能' : 'Suff.n.vs', 'Suff.n.vs' : '接尾辞-名詞的-サ変可能',
	'接尾辞-名詞的-一般' : 'Suff.n.g', 'Suff.n.g' : '接尾辞-名詞的-一般',
	'接尾辞-名詞的-副詞可能' : 'Suff.n.adv', 'Suff.n.adv' : '接尾辞-名詞的-副詞可能',
	'接尾辞-名詞的-助数詞' : 'Suff.n.count', 'Suff.n.count' : '接尾辞-名詞的-助数詞',
	'接尾辞-形容詞的' : 'Suff.ai', 'Suff.ai' : '接尾辞-形容詞的',
	'接尾辞-形状詞的' : 'Suff.ana', 'Suff.ana' : '接尾辞-形状詞的',
	'接続詞' : 'Conj', 'Conj' : '接続詞',
	'接頭辞' : 'Pref', 'Pref' : '接頭辞',
	'空白' : 'Ws', 'Ws' : '空白',
	'補助記号-ＡＡ-一般' : 'Supsym.aa.g', 'Supsym.aa.g' : '補助記号-ＡＡ-一般',
	'補助記号-ＡＡ-顔文字' : 'Supsym.aa.e', 'Supsym.aa.e' : '補助記号-ＡＡ-顔文字',
	'補助記号-一般' : 'Supsym.g', 'Supsym.g' : '補助記号-一般',
	'補助記号-句点' : 'Supsym.p', 'Supsym.p' : '補助記号-句点',
	'補助記号-括弧閉' : 'Supsym.bo', 'Supsym.bo' : '補助記号-括弧閉',
	'補助記号-括弧開' : 'Supsym.bc', 'Supsym.bc' : '補助記号-括弧開',
	'補助記号-読点' : 'Supsym.c', 'Supsym.c' : '補助記号-読点',
	'記号-一般' : 'Sym.g', 'Sym.g' : '記号-一般',
	'記号-文字' : 'Sym.ch', 'Sym.ch' : '記号-文字',
	'連体詞' : 'Adn', 'Adn' : '連体詞',
	'未知語' : 'Unknown', 'Unknown' : '未知語',
	'カタカナ文' : 'Katakana', 'Katakana' : 'カタカナ文',
	'漢文' : 'Kanbun', 'Kanbun' : '漢文',
	'言いよどみ' : 'Hesitation', 'Hesitation' : '言いよどみ',
	'web誤脱' : 'ErrorOmit', 'ErrorOmit' : 'web誤脱',
	'方言' : 'Dialect', 'Dialect' : '方言',
	'ローマ字文' : 'Lat', 'Lat' : 'ローマ字文',
	'新規未知語' : 'NewUnknown', 'NewUnknown' : '新規未知語',
};

///Convert pos enum to en
Map<PosUnidic, String> posToEn = {
	PosUnidic.Pron : 'Pron',
	PosUnidic.Adv : 'Adv',
	PosUnidic.Aux : 'Aux',
	PosUnidic.P_bind : 'P.bind',
	PosUnidic.P_adv : 'P.adv',
	PosUnidic.P_conj : 'P.conj',
	PosUnidic.P_case : 'P.case',
	PosUnidic.P_nom : 'P.nom',
	PosUnidic.P_fin : 'P.fin',
	PosUnidic.V_g : 'V.g',
	PosUnidic.V_bnd : 'V.bnd',
	PosUnidic.N_aux : 'N.aux',
	PosUnidic.N_prop_g : 'N.prop.g',
	PosUnidic.N_prop_n_g : 'N.prop.n.g',
	PosUnidic.N_prop_n_f : 'N.prop.n.f',
	PosUnidic.N_prop_n_s : 'N.prop.n.s',
	PosUnidic.N_prop_p_g : 'N.prop.p.g',
	PosUnidic.N_prop_p_c : 'N.prop.p.c',
	PosUnidic.N_num : 'N.num',
	PosUnidic.N_c_vs : 'N.c.vs',
	PosUnidic.N_c_vs_ana : 'N.c.vs.ana',
	PosUnidic.N_c_g : 'N.c.g',
	PosUnidic.N_c_adv : 'N.c.adv',
	PosUnidic.N_c_count : 'N.c.count',
	PosUnidic.N_c_ana : 'N.c.ana',
	PosUnidic.Ai_g : 'Ai.g',
	PosUnidic.Ai_bnd : 'Ai.bnd',
	PosUnidic.Ana_tari : 'Ana.tari',
	PosUnidic.Ana_g : 'Ana.g',
	PosUnidic.Ana_aux : 'Ana.aux',
	PosUnidic.Interj_fill : 'Interj.fill',
	PosUnidic.Interj_g : 'Interj.g',
	PosUnidic.Suff_v : 'Suff.v',
	PosUnidic.Suff_n_vs : 'Suff.n.vs',
	PosUnidic.Suff_n_g : 'Suff.n.g',
	PosUnidic.Suff_n_adv : 'Suff.n.adv',
	PosUnidic.Suff_n_count : 'Suff.n.count',
	PosUnidic.Suff_ai : 'Suff.ai',
	PosUnidic.Suff_ana : 'Suff.ana',
	PosUnidic.Conj : 'Conj',
	PosUnidic.Pref : 'Pref',
	PosUnidic.Ws : 'Ws',
	PosUnidic.Supsym_aa_g : 'Supsym.aa.g',
	PosUnidic.Supsym_aa_e : 'Supsym.aa.e',
	PosUnidic.Supsym_g : 'Supsym.g',
	PosUnidic.Supsym_p : 'Supsym.p',
	PosUnidic.Supsym_bo : 'Supsym.bo',
	PosUnidic.Supsym_bc : 'Supsym.bc',
	PosUnidic.Supsym_c : 'Supsym.c',
	PosUnidic.Sym_g : 'Sym.g',
	PosUnidic.Sym_ch : 'Sym.ch',
	PosUnidic.Adn : 'Adn',
	PosUnidic.Unknown : 'Unknown',
	PosUnidic.Katakana : 'Katakana',
	PosUnidic.Kanbun : 'Kanbun',
	PosUnidic.Hesitation : 'Hesitation',
	PosUnidic.ErrorOmit : 'ErrorOmit',
	PosUnidic.Dialect : 'Dialect',
	PosUnidic.Lat : 'Lat',
	PosUnidic.NewUnknown : 'NewUnknown',
};

///Convert pos enum to jp
Map<PosUnidic, String> posToJp = {
	PosUnidic.Pron : '代名詞',
	PosUnidic.Adv : '副詞',
	PosUnidic.Aux : '助動詞',
	PosUnidic.P_bind : '助詞-係助詞',
	PosUnidic.P_adv : '助詞-副助詞',
	PosUnidic.P_conj : '助詞-接続助詞',
	PosUnidic.P_case : '助詞-格助詞',
	PosUnidic.P_nom : '助詞-準体助詞',
	PosUnidic.P_fin : '助詞-終助詞',
	PosUnidic.V_g : '動詞-一般',
	PosUnidic.V_bnd : '動詞-非自立可能',
	PosUnidic.N_aux : '名詞-助動詞語幹',
	PosUnidic.N_prop_g : '名詞-固有名詞-一般',
	PosUnidic.N_prop_n_g : '名詞-固有名詞-人名-一般',
	PosUnidic.N_prop_n_f : '名詞-固有名詞-人名-名',
	PosUnidic.N_prop_n_s : '名詞-固有名詞-人名-姓',
	PosUnidic.N_prop_p_g : '名詞-固有名詞-地名-一般',
	PosUnidic.N_prop_p_c : '名詞-固有名詞-地名-国',
	PosUnidic.N_num : '名詞-数詞',
	PosUnidic.N_c_vs : '名詞-普通名詞-サ変可能',
	PosUnidic.N_c_vs_ana : '名詞-普通名詞-サ変形状詞可能',
	PosUnidic.N_c_g : '名詞-普通名詞-一般',
	PosUnidic.N_c_adv : '名詞-普通名詞-副詞可能',
	PosUnidic.N_c_count : '名詞-普通名詞-助数詞可能',
	PosUnidic.N_c_ana : '名詞-普通名詞-形状詞可能',
	PosUnidic.Ai_g : '形容詞-一般',
	PosUnidic.Ai_bnd : '形容詞-非自立可能',
	PosUnidic.Ana_tari : '形状詞-タリ',
	PosUnidic.Ana_g : '形状詞-一般',
	PosUnidic.Ana_aux : '形状詞-助動詞語幹',
	PosUnidic.Interj_fill : '感動詞-フィラー',
	PosUnidic.Interj_g : '感動詞-一般',
	PosUnidic.Suff_v : '接尾辞-動詞的',
	PosUnidic.Suff_n_vs : '接尾辞-名詞的-サ変可能',
	PosUnidic.Suff_n_g : '接尾辞-名詞的-一般',
	PosUnidic.Suff_n_adv : '接尾辞-名詞的-副詞可能',
	PosUnidic.Suff_n_count : '接尾辞-名詞的-助数詞',
	PosUnidic.Suff_ai : '接尾辞-形容詞的',
	PosUnidic.Suff_ana : '接尾辞-形状詞的',
	PosUnidic.Conj : '接続詞',
	PosUnidic.Pref : '接頭辞',
	PosUnidic.Ws : '空白',
	PosUnidic.Supsym_aa_g : '補助記号-ＡＡ-一般',
	PosUnidic.Supsym_aa_e : '補助記号-ＡＡ-顔文字',
	PosUnidic.Supsym_g : '補助記号-一般',
	PosUnidic.Supsym_p : '補助記号-句点',
	PosUnidic.Supsym_bo : '補助記号-括弧閉',
	PosUnidic.Supsym_bc : '補助記号-括弧開',
	PosUnidic.Supsym_c : '補助記号-読点',
	PosUnidic.Sym_g : '記号-一般',
	PosUnidic.Sym_ch : '記号-文字',
	PosUnidic.Adn : '連体詞',
	PosUnidic.Unknown : '未知語',
	PosUnidic.Katakana : 'カタカナ文',
	PosUnidic.Kanbun : '漢文',
	PosUnidic.Hesitation : '言いよどみ',
	PosUnidic.ErrorOmit : 'web誤脱',
	PosUnidic.Dialect : '方言',
	PosUnidic.Lat : 'ローマ字文',
	PosUnidic.NewUnknown : '新規未知語',
};

///Convert pos enum to jp
Map<PosUnidic, String> posToDesc = {
	PosUnidic.Pron : 'pronoun',
	PosUnidic.Adv : 'adverb',
	PosUnidic.Aux : 'auxiliary_verb',
	PosUnidic.P_bind : 'particle (binding)',
	PosUnidic.P_adv : 'particle (adverbial)',
	PosUnidic.P_conj : 'particle (conjunctive)',
	PosUnidic.P_case : 'particle (case)',
	PosUnidic.P_nom : 'particle (nominal)',
	PosUnidic.P_fin : 'particle (phrase_final)',
	PosUnidic.V_g : 'verb (general)',
	PosUnidic.V_bnd : 'verb (bound)',
	PosUnidic.N_aux : 'noun (auxiliary)',
	PosUnidic.N_prop_g : 'noun (proper.general)',
	PosUnidic.N_prop_n_g : 'noun (proper.name.general)',
	PosUnidic.N_prop_n_f : 'noun (proper.name.firstname)',
	PosUnidic.N_prop_n_s : 'noun (proper.name.surname)',
	PosUnidic.N_prop_p_g : 'noun (proper.place.general)',
	PosUnidic.N_prop_p_c : 'noun (proper.place.country)',
	PosUnidic.N_num : 'noun (numeral)',
	PosUnidic.N_c_vs : 'noun (common.verbal_suru)',
	PosUnidic.N_c_vs_ana : 'noun (common.verbal.adjectival)',
	PosUnidic.N_c_g : 'noun (common.general)',
	PosUnidic.N_c_adv : 'noun (common.adverbial)',
	PosUnidic.N_c_count : 'noun (common.counter)',
	PosUnidic.N_c_ana : 'noun (common.adjectival)',
	PosUnidic.Ai_g : 'adjective_i (general)',
	PosUnidic.Ai_bnd : 'adjective_i (bound)',
	PosUnidic.Ana_tari : 'adjectival_noun (tari)',
	PosUnidic.Ana_g : 'adjectival_noun (general)',
	PosUnidic.Ana_aux : 'adjectival_noun (auxiliary)',
	PosUnidic.Interj_fill : 'interjection (filler)',
	PosUnidic.Interj_g : 'interjection (general)',
	PosUnidic.Suff_v : 'suffix (verbal)',
	PosUnidic.Suff_n_vs : 'suffix (nominal.verbal_suru)',
	PosUnidic.Suff_n_g : 'suffix (nominal.general)',
	PosUnidic.Suff_n_adv : 'suffix (nominal.adverbial)',
	PosUnidic.Suff_n_count : 'suffix (nominal.counter)',
	PosUnidic.Suff_ai : 'suffix (adjective_i)',
	PosUnidic.Suff_ana : 'suffix (adjectival_noun)',
	PosUnidic.Conj : 'conjunction',
	PosUnidic.Pref : 'prefix',
	PosUnidic.Ws : 'whitespace',
	PosUnidic.Supsym_aa_g : 'supplementary_symbol (ascii_art.general)',
	PosUnidic.Supsym_aa_e : 'supplementary_symbol (ascii_art.emoticon)',
	PosUnidic.Supsym_g : 'supplementary_symbol (general)',
	PosUnidic.Supsym_p : 'supplementary_symbol (period)',
	PosUnidic.Supsym_bo : 'supplementary_symbol (bracketopen)',
	PosUnidic.Supsym_bc : 'supplementary_symbol (bracketclose)',
	PosUnidic.Supsym_c : 'supplementary_symbol (comma)',
	PosUnidic.Sym_g : 'symbol (general)',
	PosUnidic.Sym_ch : 'symbol (character)',
	PosUnidic.Adn : 'adnominal',
	PosUnidic.Unknown : 'unknown_words',
	PosUnidic.Katakana : 'katakana',
	PosUnidic.Kanbun : 'chinese_writing',
	PosUnidic.Hesitation : 'hesitation',
	PosUnidic.ErrorOmit : 'errors_omissions',
	PosUnidic.Dialect : 'dialect',
	PosUnidic.Lat : 'latin_alphabet',
	PosUnidic.NewUnknown : 'new_unknown_words',
};

