


///Contains
enum PosUnidic {
	pron,
	adv,
	aux,
	pBind,
	pAdv,
	pConj,
	pCase,
	pNom,
	pFin,
	vG,
	vBnd,
	nAux,
	nPropG,
	nPropNG,
	nPropNF,
	nPropNS,
	nPropPG,
	nPropPC,
	nNum,
	nCVs,
	nCVsAna,
	nCG,
	nCAdv,
	nCCount,
	nCAna,
	aiG,
	aiBnd,
	anaTari,
	anaG,
	anaAux,
	interjFill,
	interjG,
	suffV,
	suffNVs,
	suffNG,
	suffNAdv,
	suffNCount,
	suffAi,
	suffAna,
	conj,
	pref,
	ws,
	supsymAaG,
	supsymAaE,
	supsymG,
	supsymP,
	supsymBo,
	supsymBc,
	supsymC,
	symG,
	symCh,
	adn,
	unknown,
	katakana,
	kanbun,
	hesitation,
	errorOmit,
	dialect,
	lat,
	newUnknown,
}

///Convert a kagome output string (japanese) to an pos enum instance

Map<String, PosUnidic> jpToPosUnidic = {
	'代名詞' : PosUnidic.pron,
	'副詞' : PosUnidic.adv,
	'助動詞' : PosUnidic.aux,
	'助詞-係助詞' : PosUnidic.pBind,
	'助詞-副助詞' : PosUnidic.pAdv,
	'助詞-接続助詞' : PosUnidic.pConj,
	'助詞-格助詞' : PosUnidic.pCase,
	'助詞-準体助詞' : PosUnidic.pNom,
	'助詞-終助詞' : PosUnidic.pFin,
	'動詞-一般' : PosUnidic.vG,
	'動詞-非自立可能' : PosUnidic.vBnd,
	'名詞-助動詞語幹' : PosUnidic.nAux,
	'名詞-固有名詞-一般' : PosUnidic.nPropG,
	'名詞-固有名詞-人名-一般' : PosUnidic.nPropNG,
	'名詞-固有名詞-人名-名' : PosUnidic.nPropNF,
	'名詞-固有名詞-人名-姓' : PosUnidic.nPropNS,
	'名詞-固有名詞-地名-一般' : PosUnidic.nPropPG,
	'名詞-固有名詞-地名-国' : PosUnidic.nPropPC,
	'名詞-数詞' : PosUnidic.nNum,
	'名詞-普通名詞-サ変可能' : PosUnidic.nCVs,
	'名詞-普通名詞-サ変形状詞可能' : PosUnidic.nCVsAna,
	'名詞-普通名詞-一般' : PosUnidic.nCG,
	'名詞-普通名詞-副詞可能' : PosUnidic.nCAdv,
	'名詞-普通名詞-助数詞可能' : PosUnidic.nCCount,
	'名詞-普通名詞-形状詞可能' : PosUnidic.nCAna,
	'形容詞-一般' : PosUnidic.aiG,
	'形容詞-非自立可能' : PosUnidic.aiBnd,
	'形状詞-タリ' : PosUnidic.anaTari,
	'形状詞-一般' : PosUnidic.anaG,
	'形状詞-助動詞語幹' : PosUnidic.anaAux,
	'感動詞-フィラー' : PosUnidic.interjFill,
	'感動詞-一般' : PosUnidic.interjG,
	'接尾辞-動詞的' : PosUnidic.suffV,
	'接尾辞-名詞的-サ変可能' : PosUnidic.suffNVs,
	'接尾辞-名詞的-一般' : PosUnidic.suffNG,
	'接尾辞-名詞的-副詞可能' : PosUnidic.suffNAdv,
	'接尾辞-名詞的-助数詞' : PosUnidic.suffNCount,
	'接尾辞-形容詞的' : PosUnidic.suffAi,
	'接尾辞-形状詞的' : PosUnidic.suffAna,
	'接続詞' : PosUnidic.conj,
	'接頭辞' : PosUnidic.pref,
	'空白' : PosUnidic.ws,
	'補助記号-ＡＡ-一般' : PosUnidic.supsymAaG,
	'補助記号-ＡＡ-顔文字' : PosUnidic.supsymAaE,
	'補助記号-一般' : PosUnidic.supsymG,
	'補助記号-句点' : PosUnidic.supsymP,
	'補助記号-括弧閉' : PosUnidic.supsymBo,
	'補助記号-括弧開' : PosUnidic.supsymBc,
	'補助記号-読点' : PosUnidic.supsymC,
	'記号-一般' : PosUnidic.symG,
	'記号-文字' : PosUnidic.symCh,
	'連体詞' : PosUnidic.adn,
	'未知語' : PosUnidic.unknown,
	'カタカナ文' : PosUnidic.katakana,
	'漢文' : PosUnidic.kanbun,
	'言いよどみ' : PosUnidic.hesitation,
	'web誤脱' : PosUnidic.errorOmit,
	'方言' : PosUnidic.dialect,
	'ローマ字文' : PosUnidic.lat,
	'新規未知語' : PosUnidic.newUnknown,
};

///Convert a kagome output string (english) to an pos enum instance
Map<String, PosUnidic> enToPosUnidic = {
	'Pron' : PosUnidic.pron,
	'Adv' : PosUnidic.adv,
	'Aux' : PosUnidic.aux,
	'P.bind' : PosUnidic.pBind,
	'P.adv' : PosUnidic.pAdv,
	'P.conj' : PosUnidic.pConj,
	'P.case' : PosUnidic.pCase,
	'P.nom' : PosUnidic.pNom,
	'P.fin' : PosUnidic.pFin,
	'V.g' : PosUnidic.vG,
	'V.bnd' : PosUnidic.vBnd,
	'N.aux' : PosUnidic.nAux,
	'N.prop.g' : PosUnidic.nPropG,
	'N.prop.n.g' : PosUnidic.nPropNG,
	'N.prop.n.f' : PosUnidic.nPropNF,
	'N.prop.n.s' : PosUnidic.nPropNS,
	'N.prop.p.g' : PosUnidic.nPropPG,
	'N.prop.p.c' : PosUnidic.nPropPC,
	'N.num' : PosUnidic.nNum,
	'N.c.vs' : PosUnidic.nCVs,
	'N.c.vs.ana' : PosUnidic.nCVsAna,
	'N.c.g' : PosUnidic.nCG,
	'N.c.adv' : PosUnidic.nCAdv,
	'N.c.count' : PosUnidic.nCCount,
	'N.c.ana' : PosUnidic.nCAna,
	'Ai.g' : PosUnidic.aiG,
	'Ai.bnd' : PosUnidic.aiBnd,
	'Ana.tari' : PosUnidic.anaTari,
	'Ana.g' : PosUnidic.anaG,
	'Ana.aux' : PosUnidic.anaAux,
	'Interj.fill' : PosUnidic.interjFill,
	'Interj.g' : PosUnidic.interjG,
	'Suff.v' : PosUnidic.suffV,
	'Suff.n.vs' : PosUnidic.suffNVs,
	'Suff.n.g' : PosUnidic.suffNG,
	'Suff.n.adv' : PosUnidic.suffNAdv,
	'Suff.n.count' : PosUnidic.suffNCount,
	'Suff.ai' : PosUnidic.suffAi,
	'Suff.ana' : PosUnidic.suffAna,
	'Conj' : PosUnidic.conj,
	'Pref' : PosUnidic.pref,
	'Ws' : PosUnidic.ws,
	'Supsym.aa.g' : PosUnidic.supsymAaG,
	'Supsym.aa.e' : PosUnidic.supsymAaE,
	'Supsym.g' : PosUnidic.supsymG,
	'Supsym.p' : PosUnidic.supsymP,
	'Supsym.bo' : PosUnidic.supsymBo,
	'Supsym.bc' : PosUnidic.supsymBc,
	'Supsym.c' : PosUnidic.supsymC,
	'Sym.g' : PosUnidic.symG,
	'Sym.ch' : PosUnidic.symCh,
	'Adn' : PosUnidic.adn,
	'Unknown' : PosUnidic.unknown,
	'Katakana' : PosUnidic.katakana,
	'Kanbun' : PosUnidic.kanbun,
	'Hesitation' : PosUnidic.hesitation,
	'ErrorOmit' : PosUnidic.errorOmit,
	'Dialect' : PosUnidic.dialect,
	'Lat' : PosUnidic.lat,
	'NewUnknown' : PosUnidic.newUnknown,
};

///Convert english to japanese pos and vice versa
Map<String, String> jpEnConverter = {
	'代名詞' : 'Pron', 'Pron' : '代名詞',
	'副詞' : 'Adv', 'Adv' : '副詞',
	'助動詞' : 'Aux', 'Aux' : '助動詞',
	'助詞-係助詞' : 'P.bind', 'P.bind' : '助詞-係助詞',
	'助詞-副助詞' : 'P.adv', 'P.adv' : '助詞-副助詞',
	'助詞-接続助詞' : 'P.conj', 'P.conj' : '助詞-接続助詞',
	'助詞-格助詞' : 'P.case', 'P.case' : '助詞-格助詞',
	'助詞-準体助詞' : 'P.nom', 'P.nom' : '助詞-準体助詞',
	'助詞-終助詞' : 'P.fin', 'P.fin' : '助詞-終助詞',
	'動詞-一般' : 'V.g', 'V.g' : '動詞-一般',
	'動詞-非自立可能' : 'V.bnd', 'V.bnd' : '動詞-非自立可能',
	'名詞-助動詞語幹' : 'N.aux', 'N.aux' : '名詞-助動詞語幹',
	'名詞-固有名詞-一般' : 'N.prop.g', 'N.prop.g' : '名詞-固有名詞-一般',
	'名詞-固有名詞-人名-一般' : 'N.prop.n.g', 'N.prop.n.g' : '名詞-固有名詞-人名-一般',
	'名詞-固有名詞-人名-名' : 'N.prop.n.f', 'N.prop.n.f' : '名詞-固有名詞-人名-名',
	'名詞-固有名詞-人名-姓' : 'N.prop.n.s', 'N.prop.n.s' : '名詞-固有名詞-人名-姓',
	'名詞-固有名詞-地名-一般' : 'N.prop.p.g', 'N.prop.p.g' : '名詞-固有名詞-地名-一般',
	'名詞-固有名詞-地名-国' : 'N.prop.p.c', 'N.prop.p.c' : '名詞-固有名詞-地名-国',
	'名詞-数詞' : 'N.num', 'N.num' : '名詞-数詞',
	'名詞-普通名詞-サ変可能' : 'N.c.vs', 'N.c.vs' : '名詞-普通名詞-サ変可能',
	'名詞-普通名詞-サ変形状詞可能' : 'N.c.vs.ana', 'N.c.vs.ana' : '名詞-普通名詞-サ変形状詞可能',
	'名詞-普通名詞-一般' : 'N.c.g', 'N.c.g' : '名詞-普通名詞-一般',
	'名詞-普通名詞-副詞可能' : 'N.c.adv', 'N.c.adv' : '名詞-普通名詞-副詞可能',
	'名詞-普通名詞-助数詞可能' : 'N.c.count', 'N.c.count' : '名詞-普通名詞-助数詞可能',
	'名詞-普通名詞-形状詞可能' : 'N.c.ana', 'N.c.ana' : '名詞-普通名詞-形状詞可能',
	'形容詞-一般' : 'Ai.g', 'Ai.g' : '形容詞-一般',
	'形容詞-非自立可能' : 'Ai.bnd', 'Ai.bnd' : '形容詞-非自立可能',
	'形状詞-タリ' : 'Ana.tari', 'Ana.tari' : '形状詞-タリ',
	'形状詞-一般' : 'Ana.g', 'Ana.g' : '形状詞-一般',
	'形状詞-助動詞語幹' : 'Ana.aux', 'Ana.aux' : '形状詞-助動詞語幹',
	'感動詞-フィラー' : 'Interj.fill', 'Interj.fill' : '感動詞-フィラー',
	'感動詞-一般' : 'Interj.g', 'Interj.g' : '感動詞-一般',
	'接尾辞-動詞的' : 'Suff.v', 'Suff.v' : '接尾辞-動詞的',
	'接尾辞-名詞的-サ変可能' : 'Suff.n.vs', 'Suff.n.vs' : '接尾辞-名詞的-サ変可能',
	'接尾辞-名詞的-一般' : 'Suff.n.g', 'Suff.n.g' : '接尾辞-名詞的-一般',
	'接尾辞-名詞的-副詞可能' : 'Suff.n.adv', 'Suff.n.adv' : '接尾辞-名詞的-副詞可能',
	'接尾辞-名詞的-助数詞' : 'Suff.n.count', 'Suff.n.count' : '接尾辞-名詞的-助数詞',
	'接尾辞-形容詞的' : 'Suff.ai', 'Suff.ai' : '接尾辞-形容詞的',
	'接尾辞-形状詞的' : 'Suff.ana', 'Suff.ana' : '接尾辞-形状詞的',
	'接続詞' : 'Conj', 'Conj' : '接続詞',
	'接頭辞' : 'Pref', 'Pref' : '接頭辞',
	'空白' : 'Ws', 'Ws' : '空白',
	'補助記号-ＡＡ-一般' : 'Supsym.aa.g', 'Supsym.aa.g' : '補助記号-ＡＡ-一般',
	'補助記号-ＡＡ-顔文字' : 'Supsym.aa.e', 'Supsym.aa.e' : '補助記号-ＡＡ-顔文字',
	'補助記号-一般' : 'Supsym.g', 'Supsym.g' : '補助記号-一般',
	'補助記号-句点' : 'Supsym.p', 'Supsym.p' : '補助記号-句点',
	'補助記号-括弧閉' : 'Supsym.bo', 'Supsym.bo' : '補助記号-括弧閉',
	'補助記号-括弧開' : 'Supsym.bc', 'Supsym.bc' : '補助記号-括弧開',
	'補助記号-読点' : 'Supsym.c', 'Supsym.c' : '補助記号-読点',
	'記号-一般' : 'Sym.g', 'Sym.g' : '記号-一般',
	'記号-文字' : 'Sym.ch', 'Sym.ch' : '記号-文字',
	'連体詞' : 'Adn', 'Adn' : '連体詞',
	'未知語' : 'Unknown', 'Unknown' : '未知語',
	'カタカナ文' : 'Katakana', 'Katakana' : 'カタカナ文',
	'漢文' : 'Kanbun', 'Kanbun' : '漢文',
	'言いよどみ' : 'Hesitation', 'Hesitation' : '言いよどみ',
	'web誤脱' : 'ErrorOmit', 'ErrorOmit' : 'web誤脱',
	'方言' : 'Dialect', 'Dialect' : '方言',
	'ローマ字文' : 'Lat', 'Lat' : 'ローマ字文',
	'新規未知語' : 'NewUnknown', 'NewUnknown' : '新規未知語',
};

///Convert pos enum to en
Map<PosUnidic, String> posToEn = {
	PosUnidic.pron : 'Pron',
	PosUnidic.adv : 'Adv',
	PosUnidic.aux : 'Aux',
	PosUnidic.pBind : 'P.bind',
	PosUnidic.pAdv : 'P.adv',
	PosUnidic.pConj : 'P.conj',
	PosUnidic.pCase : 'P.case',
	PosUnidic.pNom : 'P.nom',
	PosUnidic.pFin : 'P.fin',
	PosUnidic.vG : 'V.g',
	PosUnidic.vBnd : 'V.bnd',
	PosUnidic.nAux : 'N.aux',
	PosUnidic.nPropG : 'N.prop.g',
	PosUnidic.nPropNG : 'N.prop.n.g',
	PosUnidic.nPropNF : 'N.prop.n.f',
	PosUnidic.nPropNS : 'N.prop.n.s',
	PosUnidic.nPropPG : 'N.prop.p.g',
	PosUnidic.nPropPC : 'N.prop.p.c',
	PosUnidic.nNum : 'N.num',
	PosUnidic.nCVs : 'N.c.vs',
	PosUnidic.nCVsAna : 'N.c.vs.ana',
	PosUnidic.nCG : 'N.c.g',
	PosUnidic.nCAdv : 'N.c.adv',
	PosUnidic.nCCount : 'N.c.count',
	PosUnidic.nCAna : 'N.c.ana',
	PosUnidic.aiG : 'Ai.g',
	PosUnidic.aiBnd : 'Ai.bnd',
	PosUnidic.anaTari : 'Ana.tari',
	PosUnidic.anaG : 'Ana.g',
	PosUnidic.anaAux : 'Ana.aux',
	PosUnidic.interjFill : 'Interj.fill',
	PosUnidic.interjG : 'Interj.g',
	PosUnidic.suffV : 'Suff.v',
	PosUnidic.suffNVs : 'Suff.n.vs',
	PosUnidic.suffNG : 'Suff.n.g',
	PosUnidic.suffNAdv : 'Suff.n.adv',
	PosUnidic.suffNCount : 'Suff.n.count',
	PosUnidic.suffAi : 'Suff.ai',
	PosUnidic.suffAna : 'Suff.ana',
	PosUnidic.conj : 'Conj',
	PosUnidic.pref : 'Pref',
	PosUnidic.ws : 'Ws',
	PosUnidic.supsymAaG : 'Supsym.aa.g',
	PosUnidic.supsymAaE : 'Supsym.aa.e',
	PosUnidic.supsymG : 'Supsym.g',
	PosUnidic.supsymP : 'Supsym.p',
	PosUnidic.supsymBo : 'Supsym.bo',
	PosUnidic.supsymBc : 'Supsym.bc',
	PosUnidic.supsymC : 'Supsym.c',
	PosUnidic.symG : 'Sym.g',
	PosUnidic.symCh : 'Sym.ch',
	PosUnidic.adn : 'Adn',
	PosUnidic.unknown : 'Unknown',
	PosUnidic.katakana : 'Katakana',
	PosUnidic.kanbun : 'Kanbun',
	PosUnidic.hesitation : 'Hesitation',
	PosUnidic.errorOmit : 'ErrorOmit',
	PosUnidic.dialect : 'Dialect',
	PosUnidic.lat : 'Lat',
	PosUnidic.newUnknown : 'NewUnknown',
};

///Convert pos enum to jp
Map<PosUnidic, String> posToJp = {
	PosUnidic.pron : '代名詞',
	PosUnidic.adv : '副詞',
	PosUnidic.aux : '助動詞',
	PosUnidic.pBind : '助詞-係助詞',
	PosUnidic.pAdv : '助詞-副助詞',
	PosUnidic.pConj : '助詞-接続助詞',
	PosUnidic.pCase : '助詞-格助詞',
	PosUnidic.pNom : '助詞-準体助詞',
	PosUnidic.pFin : '助詞-終助詞',
	PosUnidic.vG : '動詞-一般',
	PosUnidic.vBnd : '動詞-非自立可能',
	PosUnidic.nAux : '名詞-助動詞語幹',
	PosUnidic.nPropG : '名詞-固有名詞-一般',
	PosUnidic.nPropNG : '名詞-固有名詞-人名-一般',
	PosUnidic.nPropNF : '名詞-固有名詞-人名-名',
	PosUnidic.nPropNS : '名詞-固有名詞-人名-姓',
	PosUnidic.nPropPG : '名詞-固有名詞-地名-一般',
	PosUnidic.nPropPC : '名詞-固有名詞-地名-国',
	PosUnidic.nNum : '名詞-数詞',
	PosUnidic.nCVs : '名詞-普通名詞-サ変可能',
	PosUnidic.nCVsAna : '名詞-普通名詞-サ変形状詞可能',
	PosUnidic.nCG : '名詞-普通名詞-一般',
	PosUnidic.nCAdv : '名詞-普通名詞-副詞可能',
	PosUnidic.nCCount : '名詞-普通名詞-助数詞可能',
	PosUnidic.nCAna : '名詞-普通名詞-形状詞可能',
	PosUnidic.aiG : '形容詞-一般',
	PosUnidic.aiBnd : '形容詞-非自立可能',
	PosUnidic.anaTari : '形状詞-タリ',
	PosUnidic.anaG : '形状詞-一般',
	PosUnidic.anaAux : '形状詞-助動詞語幹',
	PosUnidic.interjFill : '感動詞-フィラー',
	PosUnidic.interjG : '感動詞-一般',
	PosUnidic.suffV : '接尾辞-動詞的',
	PosUnidic.suffNVs : '接尾辞-名詞的-サ変可能',
	PosUnidic.suffNG : '接尾辞-名詞的-一般',
	PosUnidic.suffNAdv : '接尾辞-名詞的-副詞可能',
	PosUnidic.suffNCount : '接尾辞-名詞的-助数詞',
	PosUnidic.suffAi : '接尾辞-形容詞的',
	PosUnidic.suffAna : '接尾辞-形状詞的',
	PosUnidic.conj : '接続詞',
	PosUnidic.pref : '接頭辞',
	PosUnidic.ws : '空白',
	PosUnidic.supsymAaG : '補助記号-ＡＡ-一般',
	PosUnidic.supsymAaE : '補助記号-ＡＡ-顔文字',
	PosUnidic.supsymG : '補助記号-一般',
	PosUnidic.supsymP : '補助記号-句点',
	PosUnidic.supsymBo : '補助記号-括弧閉',
	PosUnidic.supsymBc : '補助記号-括弧開',
	PosUnidic.supsymC : '補助記号-読点',
	PosUnidic.symG : '記号-一般',
	PosUnidic.symCh : '記号-文字',
	PosUnidic.adn : '連体詞',
	PosUnidic.unknown : '未知語',
	PosUnidic.katakana : 'カタカナ文',
	PosUnidic.kanbun : '漢文',
	PosUnidic.hesitation : '言いよどみ',
	PosUnidic.errorOmit : 'web誤脱',
	PosUnidic.dialect : '方言',
	PosUnidic.lat : 'ローマ字文',
	PosUnidic.newUnknown : '新規未知語',
};

///Convert pos enum to jp
Map<PosUnidic, String> posToDesc = {
	PosUnidic.pron : 'pronoun',
	PosUnidic.adv : 'adverb',
	PosUnidic.aux : 'auxiliary_verb',
	PosUnidic.pBind : 'particle (binding)',
	PosUnidic.pAdv : 'particle (adverbial)',
	PosUnidic.pConj : 'particle (conjunctive)',
	PosUnidic.pCase : 'particle (case)',
	PosUnidic.pNom : 'particle (nominal)',
	PosUnidic.pFin : 'particle (phrase_final)',
	PosUnidic.vG : 'verb (general)',
	PosUnidic.vBnd : 'verb (bound)',
	PosUnidic.nAux : 'noun (auxiliary)',
	PosUnidic.nPropG : 'noun (proper.general)',
	PosUnidic.nPropNG : 'noun (proper.name.general)',
	PosUnidic.nPropNF : 'noun (proper.name.firstname)',
	PosUnidic.nPropNS : 'noun (proper.name.surname)',
	PosUnidic.nPropPG : 'noun (proper.place.general)',
	PosUnidic.nPropPC : 'noun (proper.place.country)',
	PosUnidic.nNum : 'noun (numeral)',
	PosUnidic.nCVs : 'noun (common.verbal_suru)',
	PosUnidic.nCVsAna : 'noun (common.verbal.adjectival)',
	PosUnidic.nCG : 'noun (common.general)',
	PosUnidic.nCAdv : 'noun (common.adverbial)',
	PosUnidic.nCCount : 'noun (common.counter)',
	PosUnidic.nCAna : 'noun (common.adjectival)',
	PosUnidic.aiG : 'adjective_i (general)',
	PosUnidic.aiBnd : 'adjective_i (bound)',
	PosUnidic.anaTari : 'adjectival_noun (tari)',
	PosUnidic.anaG : 'adjectival_noun (general)',
	PosUnidic.anaAux : 'adjectival_noun (auxiliary)',
	PosUnidic.interjFill : 'interjection (filler)',
	PosUnidic.interjG : 'interjection (general)',
	PosUnidic.suffV : 'suffix (verbal)',
	PosUnidic.suffNVs : 'suffix (nominal.verbal_suru)',
	PosUnidic.suffNG : 'suffix (nominal.general)',
	PosUnidic.suffNAdv : 'suffix (nominal.adverbial)',
	PosUnidic.suffNCount : 'suffix (nominal.counter)',
	PosUnidic.suffAi : 'suffix (adjective_i)',
	PosUnidic.suffAna : 'suffix (adjectival_noun)',
	PosUnidic.conj : 'conjunction',
	PosUnidic.pref : 'prefix',
	PosUnidic.ws : 'whitespace',
	PosUnidic.supsymAaG : 'supplementary_symbol (ascii_art.general)',
	PosUnidic.supsymAaE : 'supplementary_symbol (ascii_art.emoticon)',
	PosUnidic.supsymG : 'supplementary_symbol (general)',
	PosUnidic.supsymP : 'supplementary_symbol (period)',
	PosUnidic.supsymBo : 'supplementary_symbol (bracketopen)',
	PosUnidic.supsymBc : 'supplementary_symbol (bracketclose)',
	PosUnidic.supsymC : 'supplementary_symbol (comma)',
	PosUnidic.symG : 'symbol (general)',
	PosUnidic.symCh : 'symbol (character)',
	PosUnidic.adn : 'adnominal',
	PosUnidic.unknown : 'unknown_words',
	PosUnidic.katakana : 'katakana',
	PosUnidic.kanbun : 'chinese_writing',
	PosUnidic.hesitation : 'hesitation',
	PosUnidic.errorOmit : 'errors_omissions',
	PosUnidic.dialect : 'dialect',
	PosUnidic.lat : 'latin_alphabet',
	PosUnidic.newUnknown : 'new_unknown_words',
};

