


///Contains
enum posUnidic {
	Pron,
	Adv,
	Aux,
	P_bind,
	P_adv,
	P_conj,
	P_case,
	P_nom,
	P_fin,
	V_g,
	V_bnd,
	N_aux,
	N_prop_g,
	N_prop_n_g,
	N_prop_n_f,
	N_prop_n_s,
	N_prop_p_g,
	N_prop_p_c,
	N_num,
	N_c_vs,
	N_c_vs_ana,
	N_c_g,
	N_c_adv,
	N_c_count,
	N_c_ana,
	Ai_g,
	Ai_bnd,
	Ana_tari,
	Ana_g,
	Ana_aux,
	Interj_fill,
	Interj_g,
	Suff_v,
	Suff_n_vs,
	Suff_n_g,
	Suff_n_adv,
	Suff_n_count,
	Suff_ai,
	Suff_ana,
	Conj,
	Pref,
	Ws,
	Supsym_aa_g,
	Supsym_aa_e,
	Supsym_g,
	Supsym_p,
	Supsym_bo,
	Supsym_bc,
	Supsym_c,
	Sym_g,
	Sym_ch,
	Adn,
	Unknown,
	Katakana,
	Kanbun,
	Hesitation,
	ErrorOmit,
	Dialect,
	Lat,
	NewUnknown,
}

///Convert a kagome output string (japanese) to an pos enum instance

Map<String, posUnidic> jpToposUnidic = {
	'代名詞' : posUnidic.Pron,
	'副詞' : posUnidic.Adv,
	'助動詞' : posUnidic.Aux,
	'助詞-係助詞' : posUnidic.P_bind,
	'助詞-副助詞' : posUnidic.P_adv,
	'助詞-接続助詞' : posUnidic.P_conj,
	'助詞-格助詞' : posUnidic.P_case,
	'助詞-準体助詞' : posUnidic.P_nom,
	'助詞-終助詞' : posUnidic.P_fin,
	'動詞-一般' : posUnidic.V_g,
	'動詞-非自立可能' : posUnidic.V_bnd,
	'名詞-助動詞語幹' : posUnidic.N_aux,
	'名詞-固有名詞-一般' : posUnidic.N_prop_g,
	'名詞-固有名詞-人名-一般' : posUnidic.N_prop_n_g,
	'名詞-固有名詞-人名-名' : posUnidic.N_prop_n_f,
	'名詞-固有名詞-人名-姓' : posUnidic.N_prop_n_s,
	'名詞-固有名詞-地名-一般' : posUnidic.N_prop_p_g,
	'名詞-固有名詞-地名-国' : posUnidic.N_prop_p_c,
	'名詞-数詞' : posUnidic.N_num,
	'名詞-普通名詞-サ変可能' : posUnidic.N_c_vs,
	'名詞-普通名詞-サ変形状詞可能' : posUnidic.N_c_vs_ana,
	'名詞-普通名詞-一般' : posUnidic.N_c_g,
	'名詞-普通名詞-副詞可能' : posUnidic.N_c_adv,
	'名詞-普通名詞-助数詞可能' : posUnidic.N_c_count,
	'名詞-普通名詞-形状詞可能' : posUnidic.N_c_ana,
	'形容詞-一般' : posUnidic.Ai_g,
	'形容詞-非自立可能' : posUnidic.Ai_bnd,
	'形状詞-タリ' : posUnidic.Ana_tari,
	'形状詞-一般' : posUnidic.Ana_g,
	'形状詞-助動詞語幹' : posUnidic.Ana_aux,
	'感動詞-フィラー' : posUnidic.Interj_fill,
	'感動詞-一般' : posUnidic.Interj_g,
	'接尾辞-動詞的' : posUnidic.Suff_v,
	'接尾辞-名詞的-サ変可能' : posUnidic.Suff_n_vs,
	'接尾辞-名詞的-一般' : posUnidic.Suff_n_g,
	'接尾辞-名詞的-副詞可能' : posUnidic.Suff_n_adv,
	'接尾辞-名詞的-助数詞' : posUnidic.Suff_n_count,
	'接尾辞-形容詞的' : posUnidic.Suff_ai,
	'接尾辞-形状詞的' : posUnidic.Suff_ana,
	'接続詞' : posUnidic.Conj,
	'接頭辞' : posUnidic.Pref,
	'空白' : posUnidic.Ws,
	'補助記号-ＡＡ-一般' : posUnidic.Supsym_aa_g,
	'補助記号-ＡＡ-顔文字' : posUnidic.Supsym_aa_e,
	'補助記号-一般' : posUnidic.Supsym_g,
	'補助記号-句点' : posUnidic.Supsym_p,
	'補助記号-括弧閉' : posUnidic.Supsym_bo,
	'補助記号-括弧開' : posUnidic.Supsym_bc,
	'補助記号-読点' : posUnidic.Supsym_c,
	'記号-一般' : posUnidic.Sym_g,
	'記号-文字' : posUnidic.Sym_ch,
	'連体詞' : posUnidic.Adn,
	'未知語' : posUnidic.Unknown,
	'カタカナ文' : posUnidic.Katakana,
	'漢文' : posUnidic.Kanbun,
	'言いよどみ' : posUnidic.Hesitation,
	'web誤脱' : posUnidic.ErrorOmit,
	'方言' : posUnidic.Dialect,
	'ローマ字文' : posUnidic.Lat,
	'新規未知語' : posUnidic.NewUnknown,
};

///Convert a kagome output string (english) to an pos enum instance
Map<String, posUnidic> enToposUnidic = {
	'Pron' : posUnidic.Pron,
	'Adv' : posUnidic.Adv,
	'Aux' : posUnidic.Aux,
	'P.bind' : posUnidic.P_bind,
	'P.adv' : posUnidic.P_adv,
	'P.conj' : posUnidic.P_conj,
	'P.case' : posUnidic.P_case,
	'P.nom' : posUnidic.P_nom,
	'P.fin' : posUnidic.P_fin,
	'V.g' : posUnidic.V_g,
	'V.bnd' : posUnidic.V_bnd,
	'N.aux' : posUnidic.N_aux,
	'N.prop.g' : posUnidic.N_prop_g,
	'N.prop.n.g' : posUnidic.N_prop_n_g,
	'N.prop.n.f' : posUnidic.N_prop_n_f,
	'N.prop.n.s' : posUnidic.N_prop_n_s,
	'N.prop.p.g' : posUnidic.N_prop_p_g,
	'N.prop.p.c' : posUnidic.N_prop_p_c,
	'N.num' : posUnidic.N_num,
	'N.c.vs' : posUnidic.N_c_vs,
	'N.c.vs.ana' : posUnidic.N_c_vs_ana,
	'N.c.g' : posUnidic.N_c_g,
	'N.c.adv' : posUnidic.N_c_adv,
	'N.c.count' : posUnidic.N_c_count,
	'N.c.ana' : posUnidic.N_c_ana,
	'Ai.g' : posUnidic.Ai_g,
	'Ai.bnd' : posUnidic.Ai_bnd,
	'Ana.tari' : posUnidic.Ana_tari,
	'Ana.g' : posUnidic.Ana_g,
	'Ana.aux' : posUnidic.Ana_aux,
	'Interj.fill' : posUnidic.Interj_fill,
	'Interj.g' : posUnidic.Interj_g,
	'Suff.v' : posUnidic.Suff_v,
	'Suff.n.vs' : posUnidic.Suff_n_vs,
	'Suff.n.g' : posUnidic.Suff_n_g,
	'Suff.n.adv' : posUnidic.Suff_n_adv,
	'Suff.n.count' : posUnidic.Suff_n_count,
	'Suff.ai' : posUnidic.Suff_ai,
	'Suff.ana' : posUnidic.Suff_ana,
	'Conj' : posUnidic.Conj,
	'Pref' : posUnidic.Pref,
	'Ws' : posUnidic.Ws,
	'Supsym.aa.g' : posUnidic.Supsym_aa_g,
	'Supsym.aa.e' : posUnidic.Supsym_aa_e,
	'Supsym.g' : posUnidic.Supsym_g,
	'Supsym.p' : posUnidic.Supsym_p,
	'Supsym.bo' : posUnidic.Supsym_bo,
	'Supsym.bc' : posUnidic.Supsym_bc,
	'Supsym.c' : posUnidic.Supsym_c,
	'Sym.g' : posUnidic.Sym_g,
	'Sym.ch' : posUnidic.Sym_ch,
	'Adn' : posUnidic.Adn,
	'Unknown' : posUnidic.Unknown,
	'Katakana' : posUnidic.Katakana,
	'Kanbun' : posUnidic.Kanbun,
	'Hesitation' : posUnidic.Hesitation,
	'ErrorOmit' : posUnidic.ErrorOmit,
	'Dialect' : posUnidic.Dialect,
	'Lat' : posUnidic.Lat,
	'NewUnknown' : posUnidic.NewUnknown,
};

///Convert english to japanese pos and vice versa
Map<String, String> jpEnConverter = {
	'代名詞' : 'Pron', 'Pron' : '代名詞',
	'副詞' : 'Adv', 'Adv' : '副詞',
	'助動詞' : 'Aux', 'Aux' : '助動詞',
	'助詞-係助詞' : 'P.bind', 'P.bind' : '助詞-係助詞',
	'助詞-副助詞' : 'P.adv', 'P.adv' : '助詞-副助詞',
	'助詞-接続助詞' : 'P.conj', 'P.conj' : '助詞-接続助詞',
	'助詞-格助詞' : 'P.case', 'P.case' : '助詞-格助詞',
	'助詞-準体助詞' : 'P.nom', 'P.nom' : '助詞-準体助詞',
	'助詞-終助詞' : 'P.fin', 'P.fin' : '助詞-終助詞',
	'動詞-一般' : 'V.g', 'V.g' : '動詞-一般',
	'動詞-非自立可能' : 'V.bnd', 'V.bnd' : '動詞-非自立可能',
	'名詞-助動詞語幹' : 'N.aux', 'N.aux' : '名詞-助動詞語幹',
	'名詞-固有名詞-一般' : 'N.prop.g', 'N.prop.g' : '名詞-固有名詞-一般',
	'名詞-固有名詞-人名-一般' : 'N.prop.n.g', 'N.prop.n.g' : '名詞-固有名詞-人名-一般',
	'名詞-固有名詞-人名-名' : 'N.prop.n.f', 'N.prop.n.f' : '名詞-固有名詞-人名-名',
	'名詞-固有名詞-人名-姓' : 'N.prop.n.s', 'N.prop.n.s' : '名詞-固有名詞-人名-姓',
	'名詞-固有名詞-地名-一般' : 'N.prop.p.g', 'N.prop.p.g' : '名詞-固有名詞-地名-一般',
	'名詞-固有名詞-地名-国' : 'N.prop.p.c', 'N.prop.p.c' : '名詞-固有名詞-地名-国',
	'名詞-数詞' : 'N.num', 'N.num' : '名詞-数詞',
	'名詞-普通名詞-サ変可能' : 'N.c.vs', 'N.c.vs' : '名詞-普通名詞-サ変可能',
	'名詞-普通名詞-サ変形状詞可能' : 'N.c.vs.ana', 'N.c.vs.ana' : '名詞-普通名詞-サ変形状詞可能',
	'名詞-普通名詞-一般' : 'N.c.g', 'N.c.g' : '名詞-普通名詞-一般',
	'名詞-普通名詞-副詞可能' : 'N.c.adv', 'N.c.adv' : '名詞-普通名詞-副詞可能',
	'名詞-普通名詞-助数詞可能' : 'N.c.count', 'N.c.count' : '名詞-普通名詞-助数詞可能',
	'名詞-普通名詞-形状詞可能' : 'N.c.ana', 'N.c.ana' : '名詞-普通名詞-形状詞可能',
	'形容詞-一般' : 'Ai.g', 'Ai.g' : '形容詞-一般',
	'形容詞-非自立可能' : 'Ai.bnd', 'Ai.bnd' : '形容詞-非自立可能',
	'形状詞-タリ' : 'Ana.tari', 'Ana.tari' : '形状詞-タリ',
	'形状詞-一般' : 'Ana.g', 'Ana.g' : '形状詞-一般',
	'形状詞-助動詞語幹' : 'Ana.aux', 'Ana.aux' : '形状詞-助動詞語幹',
	'感動詞-フィラー' : 'Interj.fill', 'Interj.fill' : '感動詞-フィラー',
	'感動詞-一般' : 'Interj.g', 'Interj.g' : '感動詞-一般',
	'接尾辞-動詞的' : 'Suff.v', 'Suff.v' : '接尾辞-動詞的',
	'接尾辞-名詞的-サ変可能' : 'Suff.n.vs', 'Suff.n.vs' : '接尾辞-名詞的-サ変可能',
	'接尾辞-名詞的-一般' : 'Suff.n.g', 'Suff.n.g' : '接尾辞-名詞的-一般',
	'接尾辞-名詞的-副詞可能' : 'Suff.n.adv', 'Suff.n.adv' : '接尾辞-名詞的-副詞可能',
	'接尾辞-名詞的-助数詞' : 'Suff.n.count', 'Suff.n.count' : '接尾辞-名詞的-助数詞',
	'接尾辞-形容詞的' : 'Suff.ai', 'Suff.ai' : '接尾辞-形容詞的',
	'接尾辞-形状詞的' : 'Suff.ana', 'Suff.ana' : '接尾辞-形状詞的',
	'接続詞' : 'Conj', 'Conj' : '接続詞',
	'接頭辞' : 'Pref', 'Pref' : '接頭辞',
	'空白' : 'Ws', 'Ws' : '空白',
	'補助記号-ＡＡ-一般' : 'Supsym.aa.g', 'Supsym.aa.g' : '補助記号-ＡＡ-一般',
	'補助記号-ＡＡ-顔文字' : 'Supsym.aa.e', 'Supsym.aa.e' : '補助記号-ＡＡ-顔文字',
	'補助記号-一般' : 'Supsym.g', 'Supsym.g' : '補助記号-一般',
	'補助記号-句点' : 'Supsym.p', 'Supsym.p' : '補助記号-句点',
	'補助記号-括弧閉' : 'Supsym.bo', 'Supsym.bo' : '補助記号-括弧閉',
	'補助記号-括弧開' : 'Supsym.bc', 'Supsym.bc' : '補助記号-括弧開',
	'補助記号-読点' : 'Supsym.c', 'Supsym.c' : '補助記号-読点',
	'記号-一般' : 'Sym.g', 'Sym.g' : '記号-一般',
	'記号-文字' : 'Sym.ch', 'Sym.ch' : '記号-文字',
	'連体詞' : 'Adn', 'Adn' : '連体詞',
	'未知語' : 'Unknown', 'Unknown' : '未知語',
	'カタカナ文' : 'Katakana', 'Katakana' : 'カタカナ文',
	'漢文' : 'Kanbun', 'Kanbun' : '漢文',
	'言いよどみ' : 'Hesitation', 'Hesitation' : '言いよどみ',
	'web誤脱' : 'ErrorOmit', 'ErrorOmit' : 'web誤脱',
	'方言' : 'Dialect', 'Dialect' : '方言',
	'ローマ字文' : 'Lat', 'Lat' : 'ローマ字文',
	'新規未知語' : 'NewUnknown', 'NewUnknown' : '新規未知語',
};

///Convert pos enum to en
Map<posUnidic, String> posToEn = {
	posUnidic.Pron : 'Pron',
	posUnidic.Adv : 'Adv',
	posUnidic.Aux : 'Aux',
	posUnidic.P_bind : 'P.bind',
	posUnidic.P_adv : 'P.adv',
	posUnidic.P_conj : 'P.conj',
	posUnidic.P_case : 'P.case',
	posUnidic.P_nom : 'P.nom',
	posUnidic.P_fin : 'P.fin',
	posUnidic.V_g : 'V.g',
	posUnidic.V_bnd : 'V.bnd',
	posUnidic.N_aux : 'N.aux',
	posUnidic.N_prop_g : 'N.prop.g',
	posUnidic.N_prop_n_g : 'N.prop.n.g',
	posUnidic.N_prop_n_f : 'N.prop.n.f',
	posUnidic.N_prop_n_s : 'N.prop.n.s',
	posUnidic.N_prop_p_g : 'N.prop.p.g',
	posUnidic.N_prop_p_c : 'N.prop.p.c',
	posUnidic.N_num : 'N.num',
	posUnidic.N_c_vs : 'N.c.vs',
	posUnidic.N_c_vs_ana : 'N.c.vs.ana',
	posUnidic.N_c_g : 'N.c.g',
	posUnidic.N_c_adv : 'N.c.adv',
	posUnidic.N_c_count : 'N.c.count',
	posUnidic.N_c_ana : 'N.c.ana',
	posUnidic.Ai_g : 'Ai.g',
	posUnidic.Ai_bnd : 'Ai.bnd',
	posUnidic.Ana_tari : 'Ana.tari',
	posUnidic.Ana_g : 'Ana.g',
	posUnidic.Ana_aux : 'Ana.aux',
	posUnidic.Interj_fill : 'Interj.fill',
	posUnidic.Interj_g : 'Interj.g',
	posUnidic.Suff_v : 'Suff.v',
	posUnidic.Suff_n_vs : 'Suff.n.vs',
	posUnidic.Suff_n_g : 'Suff.n.g',
	posUnidic.Suff_n_adv : 'Suff.n.adv',
	posUnidic.Suff_n_count : 'Suff.n.count',
	posUnidic.Suff_ai : 'Suff.ai',
	posUnidic.Suff_ana : 'Suff.ana',
	posUnidic.Conj : 'Conj',
	posUnidic.Pref : 'Pref',
	posUnidic.Ws : 'Ws',
	posUnidic.Supsym_aa_g : 'Supsym.aa.g',
	posUnidic.Supsym_aa_e : 'Supsym.aa.e',
	posUnidic.Supsym_g : 'Supsym.g',
	posUnidic.Supsym_p : 'Supsym.p',
	posUnidic.Supsym_bo : 'Supsym.bo',
	posUnidic.Supsym_bc : 'Supsym.bc',
	posUnidic.Supsym_c : 'Supsym.c',
	posUnidic.Sym_g : 'Sym.g',
	posUnidic.Sym_ch : 'Sym.ch',
	posUnidic.Adn : 'Adn',
	posUnidic.Unknown : 'Unknown',
	posUnidic.Katakana : 'Katakana',
	posUnidic.Kanbun : 'Kanbun',
	posUnidic.Hesitation : 'Hesitation',
	posUnidic.ErrorOmit : 'ErrorOmit',
	posUnidic.Dialect : 'Dialect',
	posUnidic.Lat : 'Lat',
	posUnidic.NewUnknown : 'NewUnknown',
};

///Convert pos enum to jp
Map<posUnidic, String> posToJp = {
	posUnidic.Pron : '代名詞',
	posUnidic.Adv : '副詞',
	posUnidic.Aux : '助動詞',
	posUnidic.P_bind : '助詞-係助詞',
	posUnidic.P_adv : '助詞-副助詞',
	posUnidic.P_conj : '助詞-接続助詞',
	posUnidic.P_case : '助詞-格助詞',
	posUnidic.P_nom : '助詞-準体助詞',
	posUnidic.P_fin : '助詞-終助詞',
	posUnidic.V_g : '動詞-一般',
	posUnidic.V_bnd : '動詞-非自立可能',
	posUnidic.N_aux : '名詞-助動詞語幹',
	posUnidic.N_prop_g : '名詞-固有名詞-一般',
	posUnidic.N_prop_n_g : '名詞-固有名詞-人名-一般',
	posUnidic.N_prop_n_f : '名詞-固有名詞-人名-名',
	posUnidic.N_prop_n_s : '名詞-固有名詞-人名-姓',
	posUnidic.N_prop_p_g : '名詞-固有名詞-地名-一般',
	posUnidic.N_prop_p_c : '名詞-固有名詞-地名-国',
	posUnidic.N_num : '名詞-数詞',
	posUnidic.N_c_vs : '名詞-普通名詞-サ変可能',
	posUnidic.N_c_vs_ana : '名詞-普通名詞-サ変形状詞可能',
	posUnidic.N_c_g : '名詞-普通名詞-一般',
	posUnidic.N_c_adv : '名詞-普通名詞-副詞可能',
	posUnidic.N_c_count : '名詞-普通名詞-助数詞可能',
	posUnidic.N_c_ana : '名詞-普通名詞-形状詞可能',
	posUnidic.Ai_g : '形容詞-一般',
	posUnidic.Ai_bnd : '形容詞-非自立可能',
	posUnidic.Ana_tari : '形状詞-タリ',
	posUnidic.Ana_g : '形状詞-一般',
	posUnidic.Ana_aux : '形状詞-助動詞語幹',
	posUnidic.Interj_fill : '感動詞-フィラー',
	posUnidic.Interj_g : '感動詞-一般',
	posUnidic.Suff_v : '接尾辞-動詞的',
	posUnidic.Suff_n_vs : '接尾辞-名詞的-サ変可能',
	posUnidic.Suff_n_g : '接尾辞-名詞的-一般',
	posUnidic.Suff_n_adv : '接尾辞-名詞的-副詞可能',
	posUnidic.Suff_n_count : '接尾辞-名詞的-助数詞',
	posUnidic.Suff_ai : '接尾辞-形容詞的',
	posUnidic.Suff_ana : '接尾辞-形状詞的',
	posUnidic.Conj : '接続詞',
	posUnidic.Pref : '接頭辞',
	posUnidic.Ws : '空白',
	posUnidic.Supsym_aa_g : '補助記号-ＡＡ-一般',
	posUnidic.Supsym_aa_e : '補助記号-ＡＡ-顔文字',
	posUnidic.Supsym_g : '補助記号-一般',
	posUnidic.Supsym_p : '補助記号-句点',
	posUnidic.Supsym_bo : '補助記号-括弧閉',
	posUnidic.Supsym_bc : '補助記号-括弧開',
	posUnidic.Supsym_c : '補助記号-読点',
	posUnidic.Sym_g : '記号-一般',
	posUnidic.Sym_ch : '記号-文字',
	posUnidic.Adn : '連体詞',
	posUnidic.Unknown : '未知語',
	posUnidic.Katakana : 'カタカナ文',
	posUnidic.Kanbun : '漢文',
	posUnidic.Hesitation : '言いよどみ',
	posUnidic.ErrorOmit : 'web誤脱',
	posUnidic.Dialect : '方言',
	posUnidic.Lat : 'ローマ字文',
	posUnidic.NewUnknown : '新規未知語',
};

///Convert pos enum to jp
Map<posUnidic, String> posToDesc = {
	posUnidic.Pron : 'pronoun',
	posUnidic.Adv : 'adverb',
	posUnidic.Aux : 'auxiliary_verb',
	posUnidic.P_bind : 'particle(binding)',
	posUnidic.P_adv : 'particle(adverbial)',
	posUnidic.P_conj : 'particle(conjunctive)',
	posUnidic.P_case : 'particle(case)',
	posUnidic.P_nom : 'particle(nominal)',
	posUnidic.P_fin : 'particle(phrase_final)',
	posUnidic.V_g : 'verb(general)',
	posUnidic.V_bnd : 'verb(bound)',
	posUnidic.N_aux : 'noun(auxiliary)',
	posUnidic.N_prop_g : 'noun(proper.general)',
	posUnidic.N_prop_n_g : 'noun(proper.name.general)',
	posUnidic.N_prop_n_f : 'noun(proper.name.firstname)',
	posUnidic.N_prop_n_s : 'noun(proper.name.surname)',
	posUnidic.N_prop_p_g : 'noun(proper.place.general)',
	posUnidic.N_prop_p_c : 'noun(proper.place.country)',
	posUnidic.N_num : 'noun(numeral)',
	posUnidic.N_c_vs : 'noun(common.verbal_suru)',
	posUnidic.N_c_vs_ana : 'noun(common.verbal.adjectival)',
	posUnidic.N_c_g : 'noun(common.general)',
	posUnidic.N_c_adv : 'noun(common.adverbial)',
	posUnidic.N_c_count : 'noun(common.counter)',
	posUnidic.N_c_ana : 'noun(common.adjectival)',
	posUnidic.Ai_g : 'adjective_i(general)',
	posUnidic.Ai_bnd : 'adjective_i(bound)',
	posUnidic.Ana_tari : 'adjectival_noun(tari)',
	posUnidic.Ana_g : 'adjectival_noun(general)',
	posUnidic.Ana_aux : 'adjectival_noun(auxiliary)',
	posUnidic.Interj_fill : 'interjection(filler)',
	posUnidic.Interj_g : 'interjection(general)',
	posUnidic.Suff_v : 'suffix(verbal)',
	posUnidic.Suff_n_vs : 'suffix(nominal.verbal_suru)',
	posUnidic.Suff_n_g : 'suffix(nominal.general)',
	posUnidic.Suff_n_adv : 'suffix(nominal.adverbial)',
	posUnidic.Suff_n_count : 'suffix(nominal.counter)',
	posUnidic.Suff_ai : 'suffix(adjective_i)',
	posUnidic.Suff_ana : 'suffix(adjectival_noun)',
	posUnidic.Conj : 'conjunction',
	posUnidic.Pref : 'prefix',
	posUnidic.Ws : 'whitespace',
	posUnidic.Supsym_aa_g : 'supplementary_symbol(ascii_art.general)',
	posUnidic.Supsym_aa_e : 'supplementary_symbol(ascii_art.emoticon)',
	posUnidic.Supsym_g : 'supplementary_symbol(general)',
	posUnidic.Supsym_p : 'supplementary_symbol(period)',
	posUnidic.Supsym_bo : 'supplementary_symbol(bracketopen)',
	posUnidic.Supsym_bc : 'supplementary_symbol(bracketclose)',
	posUnidic.Supsym_c : 'supplementary_symbol(comma)',
	posUnidic.Sym_g : 'symbol(general)',
	posUnidic.Sym_ch : 'symbol(character)',
	posUnidic.Adn : 'adnominal',
	posUnidic.Unknown : 'unknown_words',
	posUnidic.Katakana : 'katakana',
	posUnidic.Kanbun : 'chinese_writing',
	posUnidic.Hesitation : 'hesitation',
	posUnidic.ErrorOmit : 'errors_omissions',
	posUnidic.Dialect : 'dialect',
	posUnidic.Lat : 'latin_alphabet',
	posUnidic.NewUnknown : 'new_unknown_words',
};

